### PR TITLE
Add HiDPI supports

### LINKED ISSUE #65: HiDPI 支持
**功能描述**
支持HiDPI以避免界面模糊

**额外信息**
实现方式：https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms

### PR DESCRIPTION
**Pull request by 57a4c324e742**
**Purpose:**
Add HiDPI supports to avoid UI blurry for HiDPI monitor.

**Note:**
Please contributor read the the developer notes to avoid issue in future development

Fixed: #65 

@BingLingGroup

### CODE REVIEW

**Comment by ghost** [comment]
image
image

**Comment by 57a4c324e742** [comment]
@ConnectionRefused Fixed, Tested with 125%, 175% and 200% scale Please check it.

Edit:
Still small issue on 100% scale, might need manual adjust all control position to restore controls margin.

**Comment by 57a4c324e742** [comment]
@ConnectionRefused Now it should acceptable for all user from 100% scale to ∞ :)
There could be more optimize about UI, but it should be in another PR specified for UI layout optimize

**Comment by ghost** [comment]
@CrystalInternet Thank you, I will test later

**Comment by ghost** [comment]
After reviewing the code, I have the following questions
1. Is it necessary to change the size and the position of the control?
2. Or in other words, except setting the AutoScaleMode of each form's attribute to DPI and modifying App.config, does it need any more modifications?

If the answer to the question 2 is false, meaning it's unnecessary to do so, please create a new pull request about this issue and close this old one.

Chinese:
看了下代码，我有以下几点疑问
1. 为什么需要修改控件的大小、位置
2. 是否是只需要将每个表单的 AutoScaleMode 设置为 Dpi 并且修改 App.config 即可？

如果是 2 这种情况，请你重新提一个 pull request 并关掉旧的这个。

**Comment by 57a4c324e742** [comment]
@ConnectionRefused 
1. It should be necessary for old code, in the first commit, set AutoSize attribute to True will modify control size if origin size is too small for it's content. And in the last commit, I have no idea about why controls margin become smaller after set AutoScaleMode to Dpi, so i changed the value to make it looks no to much difference with before.
2. Not absolutely, set AutoSize to True might required, it will make sure control size can't smaller than it's content (the settings button's height was too small in origin code).

**Comment by BingLingGroup** [comment]
@CrystalInternet We've tested that just doing the following things can solve the high DPI problem.

1. Set the AutoScaleMode of each form's attribute to DPI. [Codes need to modifications](https://github.com/NetchX/Netch/pull/120/commits/4078aa1ac150e7e9dccd70b1cf0493b4e96694bb#diff-a55c4885c50757fff632e5c72ab11875)
2. Modify App.config. [Codes need modifications](https://github.com/NetchX/Netch/pull/120/commits/4078aa1ac150e7e9dccd70b1cf0493b4e96694bb#diff-b28ef3470b5eca43ab9853c81d6e99df)

To avoid any unnecessay changes, I will close this pull request. Please create a new pull request just about these two things I've mentioned above.

**Comment by 57a4c324e742** [comment]
@BingLingGroup 
No, it's not enough, please check screenshot below and test your self with 100% to 200% scale.
Text only show half, and margin between input was lost, that's why i changed location and size

Snipaste_2019-09-15_02-47-37
Snipaste_2019-09-15_02-47-48
Snipaste_2019-09-15_02-46-46
Snipaste_2019-09-15_02-46-58

**Comment by ghost** [comment]
200%

image

image


[Netch.x64.zip](https://github.com/NetchX/Netch/files/3613414/Netch.x64.zip)
[Netch.x86.zip](https://github.com/NetchX/Netch/files/3613415/Netch.x86.zip)

**Comment by 57a4c324e742** [comment]
@ConnectionRefused 

It looks like a Visual Studio issue, are you using 100% scale when you set AutoScaleMode to Dpi?
My default scale is 125%, the result is the screenshot in last comment.
Also tried use VisualStudio with 100% scale and set AutoScaleMode to Dpi, the result is same as your screenshot...

Finally i found "this.AutoScaleDimensions = new System.Drawing.SizeF(120F, 120F);" is based on system scale ratio rather than a fixed value.
UI looks no difference with both 100% and 200% scale if coding with 100% scale , but controls margin get smaller if coding with 125% or larger scale.
I'm not sure will this cause issue in future development. Maybe manual edit AutoScaleDimensions 
 in "*.Designer.cs" is required after set AutoScaleMode  to make sure same experience in all forms.

**Comment by 57a4c324e742** [comment]
And i found this → https://stackoverflow.com/a/4076259
> Always edit/design your apps in default 96 DPI (100%). If you design in 120DPI (125% f.ex) it will get really bad when you go back to 96 DPI to work with it later.

Microsoft's document never tell us this.

If you think it's ok, i will create a new PR later.

**Comment by ghost** [comment]
@CrystalInternet System: Win10 1903 Professional Workstation x64

1. Set each form AutoScaleMode to Dpi
2. Write App.config PreMonitorV2

Looks great at 100% to 200% Dpi (Tested)

**Comment by ghost** [comment]
@CrystalInternet The effect at 200% Dpi is shown above. Maybe you modified something else?

**Comment by 57a4c324e742** [comment]
@ConnectionRefused 
As i wrote above, if you **do step 1 with 100% scale**, it will **perfect** without problem, but if you are **using 125% scale on your system during change AutoScaleMode**, it will **looks like my screenshot**  (i am using 125% on my system).

It looks like a Visual Studio issue, and the solution is set `AutoScaleDimensions` to `96F` (Visual Studio not launch with 100% scale) or set system scale to 100% (things become really small...).
If you understand and accept above problem/limit, i will submit a new PR later.

**Comment by ghost** [comment]
We will wait for your PR and then release it in the next version.

**Comment by BingLingGroup** [comment]
@CrystalInternet We are looking forward to your new pull request. We've decided to release a new version soon after your new pull request has been merged.

**Comment by ghost** [comment]
We added HiDPI support at [334717d](https://github.com/NetchX/Netch/commit/334717dbe804ae7d4747bfde641930d8df039547)

Thanks for your contribution to this project

**Pull request closed without merging**
